import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// `getRouter`, not a module-level `router`: TanStack Start calls this once per REQUEST on the
// server, and a shared instance would leak one render's loaded data into the next. The name is
// the convention Start's plugin looks for in `src/router.tsx`.
//
// `routeTree.gen.ts` is generated by the Start plugin from `src/routes/`, and is excluded from
// biome by one pattern in the repo-root biome.json — the same arrangement the sibling repo runs.
//
// LINE comments, not a block comment. That biome pattern is `!` then `**` then `/routeTree...`,
// and the `*` `/` in the middle of it closes a `/*` block early: `vite build` reported
// "Unterminated string" at this line with the paragraph written the other way.
export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: 'intent',
  })
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
