import type { AccrualBody } from '../lib/client.ts'
import {
  Citations,
  type Save,
  type SectionProps,
  SectionShell,
  seedMeasured,
  toMeasured,
  useSection,
} from './common.tsx'
import {
  AmountField,
  blankToNull,
  MeasuredFields,
  type MeasuredForm,
  numberOf,
  ProseField,
  textOf,
} from './fields.tsx'

interface AccrualForm {
  accrualSegmentRevenueUsd: string
  accrualCaptureShare: string
  accrualPct: string
  accrualAnnualIssuanceUsd: string
  accrualAbsentReason: string
  accrualRationale: string
  accrualFinding: string
  marketCap: MeasuredForm
}

export function AccrualSection({
  bounds,
  citations,
  disabled,
  onAddCitation,
  onRemoveCitation,
  onSave,
  scores,
}: SectionProps & { onSave: Save<AccrualBody> }) {
  const section = useSection<AccrualForm, AccrualBody>(
    () => ({
      accrualSegmentRevenueUsd: numberOf(scores.accrualSegmentRevenueUsd),
      accrualCaptureShare: numberOf(scores.accrualCaptureShare),
      accrualPct: numberOf(scores.accrualPct),
      accrualAnnualIssuanceUsd: numberOf(scores.accrualAnnualIssuanceUsd),
      accrualAbsentReason: textOf(scores.accrualAbsentReason),
      accrualRationale: textOf(scores.accrualRationale),
      accrualFinding: textOf(scores.accrualFinding),
      marketCap: seedMeasured(
        scores.discoveryMarketCapUsd,
        scores.discoveryMarketCapSource,
        scores.discoveryMarketCapUrl,
        scores.discoveryMarketCapLabel,
        scores.discoveryMarketCapMeasuredAt,
      ),
    }),
    (form) => ({
      accrualSegmentRevenueUsd: blankToNull(form.accrualSegmentRevenueUsd),
      accrualCaptureShare: blankToNull(form.accrualCaptureShare),
      accrualPct: blankToNull(form.accrualPct),
      accrualAnnualIssuanceUsd: blankToNull(form.accrualAnnualIssuanceUsd),
      accrualAbsentReason: blankToNull(form.accrualAbsentReason),
      accrualRationale: blankToNull(form.accrualRationale),
      accrualFinding: blankToNull(form.accrualFinding),
      marketCap: toMeasured(form.marketCap),
    }),
    onSave,
  )
  const { form, update } = section

  return (
    <SectionShell
      dirty={section.dirty}
      disabled={disabled}
      error={section.error}
      onSave={section.onSave}
      saving={section.saving}
      title="5 · Value accrual and discovery premium"
    >
      <p className="mb-3 text-sm text-neutral-600">
        Cash-flow accrual only. Capture share and token accrual are FRACTIONS in [0, 1] — a value
        typed on a 0–100 scale is rejected, not divided. Leaving all four blank is a different state
        from a measured zero: say why instead, in the box below.{' '}
        <strong>Assessed: {scores.accrualAssessed ? 'yes' : 'no'}</strong> (generated by the
        database from the four inputs).
      </p>
      <AmountField
        caption="USD per year"
        disabled={disabled}
        label="Segment revenue"
        onChange={(value) => update({ ...form, accrualSegmentRevenueUsd: value })}
        value={form.accrualSegmentRevenueUsd}
      />
      <Citations
        citations={citations}
        disabled={disabled}
        field={bounds.citableFields.accrualSegmentRevenueUsd}
        label="Evidence for segment revenue"
        onAdd={onAddCitation}
        onRemove={onRemoveCitation}
      />
      <AmountField
        caption="fraction in [0, 1]"
        disabled={disabled}
        label="Capture share"
        onChange={(value) => update({ ...form, accrualCaptureShare: value })}
        value={form.accrualCaptureShare}
      />
      <AmountField
        caption="fraction in [0, 1], despite the name"
        disabled={disabled}
        label="Token accrual"
        onChange={(value) => update({ ...form, accrualPct: value })}
        value={form.accrualPct}
      />
      <AmountField
        caption="USD per year"
        disabled={disabled}
        label="Annual issuance"
        onChange={(value) => update({ ...form, accrualAnnualIssuanceUsd: value })}
        value={form.accrualAnnualIssuanceUsd}
      />
      <ProseField
        disabled={disabled}
        label="Why there is no accrual figure (required when the four boxes are not all filled)"
        onChange={(value) => update({ ...form, accrualAbsentReason: value })}
        value={form.accrualAbsentReason}
      />
      <ProseField
        disabled={disabled}
        label="Accrual rationale — name the mechanism"
        onChange={(value) => update({ ...form, accrualRationale: value })}
        value={form.accrualRationale}
      />
      <ProseField
        disabled={disabled}
        label="Accrual finding (optional prose)"
        onChange={(value) => update({ ...form, accrualFinding: value })}
        value={form.accrualFinding}
      />
      <MeasuredFields
        disabled={disabled}
        form={form.marketCap}
        label="Market cap"
        onChange={(marketCap) => update({ ...form, marketCap })}
        provenanceLabels={bounds.provenanceLabels}
      />
      <Citations
        citations={citations}
        disabled={disabled}
        field={bounds.citableFields.discoveryMarketCapUsd}
        label="Evidence for market cap"
        onAdd={onAddCitation}
        onRemove={onRemoveCitation}
      />
    </SectionShell>
  )
}
